"""companies (B1): hồ sơ doanh nghiệp có cấu trúc + thị trường xuất khẩu, ngôn ngữ (N-N).

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29 19:30:48.419238
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("exporter", "buyer", name="company_type"), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("registration_number", sa.String(length=64), nullable=True),
        sa.Column("tax_id", sa.String(length=32), nullable=True),
        sa.Column("business_type", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("industry_sector", sa.String(length=32), nullable=True),
        sa.Column("founded_year", sa.SmallInteger(), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("description_vi", sa.Text(), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("logo_key", sa.String(length=255), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum("unverified", "pending", "verified", "rejected", name="verification_status"),
            server_default="unverified",
            nullable=False,
        ),
        sa.Column(
            "verification_level",
            sa.Enum("basic", "evfta_verified", name="verification_level"),
            server_default="basic",
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "profile_completeness_score",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_companies_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("owner_user_id", name=op.f("uq_companies_owner_user_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_companies_slug")),
    )
    op.create_index(op.f("ix_companies_country"), "companies", ["country"], unique=False)
    op.create_index(
        op.f("ix_companies_industry_sector"), "companies", ["industry_sector"], unique=False
    )
    op.create_index(
        op.f("ix_companies_verification_status"), "companies", ["verification_status"], unique=False
    )
    op.create_table(
        "company_export_markets",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_export_markets_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("company_id", "market", name=op.f("pk_company_export_markets")),
    )
    op.create_index(
        op.f("ix_company_export_markets_market"), "company_export_markets", ["market"], unique=False
    )
    op.create_table(
        "company_languages",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("lang", sa.String(length=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_languages_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("company_id", "lang", name=op.f("pk_company_languages")),
    )
    op.create_index(op.f("ix_company_languages_lang"), "company_languages", ["lang"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_company_languages_lang"), table_name="company_languages")
    op.drop_table("company_languages")
    op.drop_index(op.f("ix_company_export_markets_market"), table_name="company_export_markets")
    op.drop_table("company_export_markets")
    op.drop_index(op.f("ix_companies_verification_status"), table_name="companies")
    op.drop_index(op.f("ix_companies_industry_sector"), table_name="companies")
    op.drop_index(op.f("ix_companies_country"), table_name="companies")
    op.drop_table("companies")
    for enum in ("verification_level", "verification_status", "company_type"):
        sa.Enum(name=enum).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
