"""buyer profile (B2): quy mô, ước lượng mua hàng, mã VAT, nhóm hàng quan tâm (N-N).

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-29 19:55:06.915207
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_sourcing_categories",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_sourcing_categories_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "company_id", "category", name=op.f("pk_company_sourcing_categories")
        ),
    )
    op.create_index(
        op.f("ix_company_sourcing_categories_category"),
        "company_sourcing_categories",
        ["category"],
        unique=False,
    )
    op.add_column("companies", sa.Column("company_size", sa.String(length=16), nullable=True))
    op.add_column(
        "companies", sa.Column("procurement_estimate", sa.String(length=16), nullable=True)
    )
    op.add_column("companies", sa.Column("vat_number", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "vat_number")
    op.drop_column("companies", "procurement_estimate")
    op.drop_column("companies", "company_size")
    op.drop_index(
        op.f("ix_company_sourcing_categories_category"), table_name="company_sourcing_categories"
    )
    op.drop_table("company_sourcing_categories")
    # ### end Alembic commands ###
