"""tariff_lines

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-29 22:15:10.045409
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tariff_lines",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hs_code", sa.String(length=8), nullable=False),
        sa.Column("destination", sa.String(length=2), nullable=False),
        sa.Column(
            "duty_type",
            sa.Enum("ad_valorem", "specific", "mixed", name="duty_type"),
            nullable=False,
        ),
        sa.Column("mfn_rate", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("mfn_specific", sa.String(length=255), nullable=True),
        sa.Column("evfta_rate_current", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("staging_category", sa.String(length=16), nullable=True),
        sa.Column("zero_from", sa.Date(), nullable=True),
        sa.Column("quota_required", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("quota_note", sa.Text(), nullable=True),
        sa.Column("condition_note", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "destination ~ '^[A-Z]{2}$'", name=op.f("ck_tariff_lines_destination_iso2")
        ),
        sa.CheckConstraint(
            "(mfn_rate IS NULL OR mfn_rate BETWEEN 0 AND 100) AND (evfta_rate_current IS NULL OR evfta_rate_current BETWEEN 0 AND 100)",
            name=op.f("ck_tariff_lines_rates_are_percentages"),
        ),
        sa.CheckConstraint(
            "(reviewed_by IS NULL) = (reviewed_at IS NULL)",
            name=op.f("ck_tariff_lines_reviewed_by_and_at_together"),
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name=op.f("ck_tariff_lines_valid_window"),
        ),
        sa.ForeignKeyConstraint(
            ["hs_code"], ["hs_codes.code"], name=op.f("fk_tariff_lines_hs_code_hs_codes")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_tariff_lines_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariff_lines")),
    )
    op.create_index(op.f("ix_tariff_lines_hs_code"), "tariff_lines", ["hs_code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tariff_lines_hs_code"), table_name="tariff_lines")
    op.drop_table("tariff_lines")
    op.execute("DROP TYPE IF EXISTS duty_type")
    # ### end Alembic commands ###
