"""product_specific_rules

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-29 22:50:44.915381
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_specific_rules",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hs_code", sa.String(length=8), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum("WO", "CTH", "MaxNOM", "CTH_OR_MaxNOM", name="rule_type"),
            nullable=False,
        ),
        sa.Column("threshold_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rule_text", sa.Text(), nullable=True),
        sa.Column("requires_expert", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source", sa.String(length=1024), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(rule_type IN ('MaxNOM', 'CTH_OR_MaxNOM')"
            " AND threshold_pct IS NOT NULL AND threshold_pct > 0 AND threshold_pct <= 100)"
            " OR (rule_type IN ('WO', 'CTH') AND threshold_pct IS NULL)",
            name=op.f("ck_product_specific_rules_threshold_matches_rule_type"),
        ),
        sa.CheckConstraint(
            "(reviewed_by IS NULL) = (reviewed_at IS NULL)",
            name=op.f("ck_product_specific_rules_reviewed_by_and_at_together"),
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name=op.f("ck_product_specific_rules_valid_window"),
        ),
        sa.ForeignKeyConstraint(
            ["hs_code"], ["hs_codes.code"], name=op.f("fk_product_specific_rules_hs_code_hs_codes")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_product_specific_rules_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_specific_rules")),
    )
    op.create_index(
        op.f("ix_product_specific_rules_hs_code"),
        "product_specific_rules",
        ["hs_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_specific_rules_hs_code"), table_name="product_specific_rules")
    op.drop_table("product_specific_rules")
    op.execute("DROP TYPE IF EXISTS rule_type")
    # ### end Alembic commands ###
