"""verification_decisions

Revision ID: b89c4e770a4c
Revises: 0011
Create Date: 2026-09-29 23:07:17.277153
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_decisions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum("approve", "reject", "request_info", "expire", name="verification_decision"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("from_status", sa.String(length=16), nullable=False),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("from_level", sa.String(length=16), nullable=False),
        sa.Column("to_level", sa.String(length=16), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approve', 'expire')"
            " OR (reason IS NOT NULL AND length(btrim(reason)) > 0)",
            name=op.f("ck_verification_decisions_reason_required"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_verification_decisions_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_verification_decisions_reviewer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_decisions")),
    )
    op.create_index(
        op.f("ix_verification_decisions_company_id"),
        "verification_decisions",
        ["company_id"],
        unique=False,
    )
    # forbid_mutation() tạo ở migration 0002.
    op.execute(
        "CREATE TRIGGER verification_decisions_append_only BEFORE UPDATE OR DELETE "
        "ON verification_decisions FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER verification_decisions_no_truncate BEFORE TRUNCATE "
        "ON verification_decisions FOR EACH STATEMENT EXECUTE FUNCTION forbid_mutation()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_decisions_company_id"), table_name="verification_decisions")
    op.drop_table("verification_decisions")
    op.execute("DROP TYPE IF EXISTS verification_decision")
    # ### end Alembic commands ###
