"""evidences

Revision ID: ca61eaf2a501
Revises: 0013
Create Date: 2026-09-29 23:15:06.214929
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hệ thống nâng/hạ mức evfta_verified theo bằng chứng (chỉ qua verification.service.decide()).
    op.execute("ALTER TYPE verification_decision ADD VALUE IF NOT EXISTS 'level_up'")
    op.execute("ALTER TYPE verification_decision ADD VALUE IF NOT EXISTS 'level_down'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_types",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name_vi", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column("group", sa.String(length=32), nullable=False),
        sa.Column("validity_months", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(reviewed_by IS NULL) = (reviewed_at IS NULL)",
            name=op.f("ck_evidence_types_reviewed_by_and_at_together"),
        ),
        sa.CheckConstraint(
            "validity_months IS NULL OR validity_months > 0",
            name=op.f("ck_evidence_types_positive_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_evidence_types_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_evidence_types")),
    )
    op.create_table(
        "evidences",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("type_code", sa.String(length=64), nullable=False),
        sa.Column("file_key", sa.String(length=512), nullable=False),
        sa.Column("certificate_number", sa.String(length=128), nullable=True),
        sa.Column("issuer", sa.String(length=255), nullable=True),
        sa.Column("issued_at", sa.Date(), nullable=False),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column(
            "approval_status",
            sa.Enum("pending", "approved", "rejected", name="evidence_approval_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > issued_at", name=op.f("ck_evidences_valid_window")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_evidences_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_evidences_reviewed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["type_code"],
            ["evidence_types.code"],
            name=op.f("fk_evidences_type_code_evidence_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidences")),
    )
    op.create_index(op.f("ix_evidences_company_id"), "evidences", ["company_id"], unique=False)
    op.create_table(
        "required_evidence_rules",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("evidence_type_code", sa.String(length=64), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(reviewed_by IS NULL) = (reviewed_at IS NULL)",
            name=op.f("ck_required_evidence_rules_reviewed_by_and_at_together"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_type_code"],
            ["evidence_types.code"],
            name=op.f("fk_required_evidence_rules_evidence_type_code_evidence_types"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_required_evidence_rules_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_required_evidence_rules")),
        sa.UniqueConstraint("category", "evidence_type_code", name="category_type"),
    )
    op.create_index(
        op.f("ix_required_evidence_rules_category"),
        "required_evidence_rules",
        ["category"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_required_evidence_rules_category"), table_name="required_evidence_rules")
    op.drop_table("required_evidence_rules")
    op.drop_index(op.f("ix_evidences_company_id"), table_name="evidences")
    op.drop_table("evidences")
    op.drop_table("evidence_types")
    op.execute("DROP TYPE IF EXISTS evidence_approval_status")
    # Giá trị enum verification_decision thêm ở upgrade không gỡ được (PostgreSQL không hỗ trợ).
    # ### end Alembic commands ###
