"""verification_requests

Revision ID: 09f2dc011559
Revises: 0015
Create Date: 2026-09-29 23:41:02.030916
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("ALTER TYPE verification_decision ADD VALUE IF NOT EXISTS 'submit'")
    # Lý do chỉ bắt buộc khi từ chối và yêu cầu bổ sung (nộp yêu cầu, quyết định hệ thống: không).
    op.drop_constraint(op.f("ck_verification_decisions_reason_required"), "verification_decisions")
    op.create_check_constraint(
        op.f("ck_verification_decisions_reason_required"),
        "verification_decisions",
        "decision NOT IN ('reject', 'request_info')"
        " OR (reason IS NOT NULL AND length(btrim(reason)) > 0)",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_requests",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "submitted_evidence_ids",
            sa.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "info_requested",
                name="verification_request_status",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_verification_requests_company_id_companies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_requests")),
    )
    op.create_index(
        op.f("ix_verification_requests_company_id"),
        "verification_requests",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_requests_status"), "verification_requests", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_requests_status"), table_name="verification_requests")
    op.drop_index(op.f("ix_verification_requests_company_id"), table_name="verification_requests")
    op.drop_constraint(op.f("ck_verification_decisions_reason_required"), "verification_decisions")
    op.create_check_constraint(
        op.f("ck_verification_decisions_reason_required"),
        "verification_decisions",
        "decision IN ('approve', 'expire') OR (reason IS NOT NULL AND length(btrim(reason)) > 0)",
    )
    op.drop_table("verification_requests")
    op.execute("DROP TYPE IF EXISTS verification_request_status")
    # Giá trị 'submit' của verification_decision không gỡ được (PostgreSQL không hỗ trợ).
    # ### end Alembic commands ###
