"""verification_request_reason

Revision ID: 5b41ec31853d
Revises: 0016
Create Date: 2026-09-29 23:47:04.275046
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("verification_requests", sa.Column("decision_reason", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verification_requests", "decision_reason")
    # ### end Alembic commands ###
