"""corpus

Revision ID: 18709eac7016
Revises: 0019
Create Date: 2026-09-30 00:25:47.936288
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corpus_documents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("doc_type", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column(
            "hs_codes",
            sa.ARRAY(sa.String(length=8)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "doc_type IN ('law', 'guidance', 'faq')", name=op.f("ck_corpus_documents_doc_type")
        ),
        sa.CheckConstraint("language IN ('vi', 'en')", name=op.f("ck_corpus_documents_language")),
        sa.CheckConstraint(
            "(reviewed_by IS NULL) = (reviewed_at IS NULL)",
            name=op.f("ck_corpus_documents_reviewed_by_and_at_together"),
        ),
        sa.CheckConstraint(
            "length(btrim(source)) > 0", name=op.f("ck_corpus_documents_source_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_corpus_documents_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corpus_documents")),
        sa.UniqueConstraint("source", "language", name="source_language"),
    )
    op.create_table(
        "corpus_chunks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=512), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_label", sa.String(length=600), nullable=False),
        sa.Column(
            "hs_codes",
            sa.ARRAY(sa.String(length=8)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.CheckConstraint(
            "length(btrim(source_label)) > 0", name=op.f("ck_corpus_chunks_source_label_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["corpus_documents.id"],
            name=op.f("fk_corpus_chunks_document_id_corpus_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corpus_chunks")),
    )
    op.create_index("ix_corpus_chunks_document_id", "corpus_chunks", ["document_id"], unique=False)
    # Tìm gần nhất theo cosine (D1); HNSW cho phép truy vấn nhanh khi corpus lớn.
    op.execute(
        "CREATE INDEX ix_corpus_chunks_embedding_hnsw ON corpus_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_corpus_chunks_embedding_hnsw")
    op.drop_index("ix_corpus_chunks_document_id", table_name="corpus_chunks")
    op.drop_table("corpus_chunks")
    op.drop_table("corpus_documents")
    # ### end Alembic commands ###
