"""ai_queries

Revision ID: c5d375537ad6
Revises: 0020
Create Date: 2026-09-30 00:31:22.313542
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_queries",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("hs_code", sa.String(length=8), nullable=True),
        sa.Column(
            "retrieved_chunk_ids",
            sa.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column(
            "citation_ids",
            sa.ARRAY(sa.Uuid()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("self_assessment", sa.String(length=16), nullable=True),
        sa.Column("error", sa.String(length=64), nullable=True),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IN ('high', 'medium', 'low', 'out_of_scope')",
            name=op.f("ck_ai_queries_confidence_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_ai_queries_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_queries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_queries")),
    )
    op.create_index(op.f("ix_ai_queries_confidence"), "ai_queries", ["confidence"], unique=False)
    op.create_index(op.f("ix_ai_queries_created_at"), "ai_queries", ["created_at"], unique=False)
    op.create_table(
        "ai_query_feedback",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("was_helpful", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["query_id"], ["ai_queries.id"], name=op.f("fk_ai_query_feedback_query_id_ai_queries")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_query_feedback")),
    )
    op.create_index(
        op.f("ix_ai_query_feedback_query_id"), "ai_query_feedback", ["query_id"], unique=False
    )
    op.create_table(
        "escalation_tickets",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["query_id"], ["ai_queries.id"], name=op.f("fk_escalation_tickets_query_id_ai_queries")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_escalation_tickets_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escalation_tickets")),
    )
    op.create_index(
        op.f("ix_escalation_tickets_query_id"), "escalation_tickets", ["query_id"], unique=False
    )
    # forbid_mutation() tạo ở migration 0002: ai_queries và ai_query_feedback chỉ ghi thêm.
    for table in ("ai_queries", "ai_query_feedback"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION forbid_mutation()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_escalation_tickets_query_id"), table_name="escalation_tickets")
    op.drop_table("escalation_tickets")
    op.drop_index(op.f("ix_ai_query_feedback_query_id"), table_name="ai_query_feedback")
    op.drop_table("ai_query_feedback")
    op.drop_index(op.f("ix_ai_queries_created_at"), table_name="ai_queries")
    op.drop_index(op.f("ix_ai_queries_confidence"), table_name="ai_queries")
    op.drop_table("ai_queries")
    # ### end Alembic commands ###
