"""rfqs

Revision ID: 0024
Revises: 0023
Create Date: 2026-09-30 01:23:20.294374
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0024"
down_revision: str | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rfqs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("buyer_company_id", sa.Uuid(), nullable=False),
        sa.Column("exporter_company_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="EUR", nullable=False),
        sa.Column(
            "incoterms",
            sa.Enum(
                "EXW",
                "FCA",
                "FAS",
                "FOB",
                "CFR",
                "CIF",
                "CPT",
                "CIP",
                "DAP",
                "DPU",
                "DDP",
                name="incoterm",
            ),
            nullable=False,
        ),
        sa.Column("destination_country", sa.String(length=2), nullable=False),
        sa.Column("destination_port", sa.String(length=100), nullable=True),
        sa.Column("required_date", sa.Date(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("new", "viewed", "quoted", "closed", name="rfq_status"),
            server_default="new",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "buyer_company_id <> exporter_company_id", name=op.f("ck_rfqs_different_companies")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_rfqs_positive_quantity")),
        sa.CheckConstraint(
            "target_price IS NULL OR target_price > 0", name=op.f("ck_rfqs_positive_target_price")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_company_id"], ["companies.id"], name=op.f("fk_rfqs_buyer_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["exporter_company_id"],
            ["companies.id"],
            name=op.f("fk_rfqs_exporter_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_rfqs_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfqs")),
    )
    op.create_index(
        "ix_rfqs_buyer_created", "rfqs", ["buyer_company_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_rfqs_exporter_status_created",
        "rfqs",
        ["exporter_company_id", "status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rfqs_exporter_status_created", table_name="rfqs")
    op.drop_index("ix_rfqs_buyer_created", table_name="rfqs")
    op.drop_table("rfqs")
    op.execute("DROP TYPE rfq_status")
    op.execute("DROP TYPE incoterm")
    # ### end Alembic commands ###
