"""conversations messages

Revision ID: 0025
Revises: 0024
Create Date: 2026-09-30 01:33:30.426422
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0025"
down_revision: str | None = "0024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("rfq_id", sa.Uuid(), nullable=False),
        sa.Column("company_a_id", sa.Uuid(), nullable=False),
        sa.Column("company_b_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_a_id"], ["companies.id"], name=op.f("fk_conversations_company_a_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["company_b_id"], ["companies.id"], name=op.f("fk_conversations_company_b_id_companies")
        ),
        sa.ForeignKeyConstraint(["rfq_id"], ["rfqs.id"], name=op.f("fk_conversations_rfq_id_rfqs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("rfq_id", name=op.f("uq_conversations_rfq_id")),
    )
    op.create_index("ix_conversations_company_a", "conversations", ["company_a_id"], unique=False)
    op.create_index("ix_conversations_company_b", "conversations", ["company_b_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sender_company_id", sa.Uuid(), nullable=False),
        sa.Column("body_original", sa.Text(), nullable=False),
        sa.Column("body_translated", sa.Text(), nullable=True),
        sa.Column("original_language", sa.String(length=2), nullable=False),
        sa.Column("translated_language", sa.String(length=2), nullable=True),
        sa.Column(
            "sent_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(body_translated IS NULL) = (translated_language IS NULL)",
            name=op.f("ck_messages_translation_and_language_together"),
        ),
        sa.CheckConstraint(
            "length(btrim(body_original)) > 0", name=op.f("ck_messages_body_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["sender_company_id"],
            ["companies.id"],
            name=op.f("fk_messages_sender_company_id_companies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_conversation_sent",
        "messages",
        ["conversation_id", "sent_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_conversation_sent", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_conversations_company_b", table_name="conversations")
    op.drop_index("ix_conversations_company_a", table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
