"""profile views dashboard events

Revision ID: 0026
Revises: 0025
Create Date: 2026-09-30 01:57:34.522933
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0026"
down_revision: str | None = "0025"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_events",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "opened_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("is_return_visit", sa.Boolean(), nullable=False),
        sa.Column("had_new_info", sa.Boolean(), nullable=False),
        sa.Column("tile_hashes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_dashboard_events_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_events")),
    )
    op.create_index(
        "ix_dashboard_events_user_opened",
        "dashboard_events",
        ["user_id", "opened_at"],
        unique=False,
    )
    op.create_table(
        "profile_views",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("viewer_company_id", sa.Uuid(), nullable=True),
        sa.Column(
            "viewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_profile_views_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["viewer_company_id"],
            ["companies.id"],
            name=op.f("fk_profile_views_viewer_company_id_companies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_views")),
    )
    op.create_index(
        "ix_profile_views_company_viewed",
        "profile_views",
        ["company_id", "viewed_at"],
        unique=False,
    )
    op.create_index(
        "ix_profile_views_viewer_viewed",
        "profile_views",
        ["viewer_company_id", "viewed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_profile_views_viewer_viewed", table_name="profile_views")
    op.drop_index("ix_profile_views_company_viewed", table_name="profile_views")
    op.drop_table("profile_views")
    op.drop_index("ix_dashboard_events_user_opened", table_name="dashboard_events")
    op.drop_table("dashboard_events")
    # ### end Alembic commands ###
