"""cross checks

Revision ID: 0028
Revises: 0027
Create Date: 2026-09-30 11:47:46.368367
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0028"
down_revision: str | None = "0027"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # I8: hai loại kiểm mới (giá trị enum chưa dùng trong cùng transaction nên an toàn).
    op.execute("ALTER TYPE evidence_check_type ADD VALUE IF NOT EXISTS 'issuer_email'")
    op.execute("ALTER TYPE evidence_check_type ADD VALUE IF NOT EXISTS 'internal_consistency'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certification_bodies",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("official_domain", sa.String(length=255), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.Column("lookup_url", sa.String(length=512), nullable=True),
        sa.Column("accreditation_body", sa.String(length=255), nullable=True),
        sa.Column("iaf_mla", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(reviewed_by IS NULL) = (reviewed_at IS NULL)",
            name=op.f("ck_certification_bodies_reviewed_by_and_at_together"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_certification_bodies_reviewed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certification_bodies")),
        sa.UniqueConstraint("name", name=op.f("uq_certification_bodies_name")),
    )
    op.add_column("evidence_checks", sa.Column("source", sa.Text(), nullable=True))
    op.add_column("evidence_checks", sa.Column("certification_body_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_evidence_checks_certification_body_id_certification_bodies"),
        "evidence_checks",
        "certification_bodies",
        ["certification_body_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_evidence_checks_certification_body_id_certification_bodies"),
        "evidence_checks",
        type_="foreignkey",
    )
    op.drop_column("evidence_checks", "certification_body_id")
    op.drop_column("evidence_checks", "source")
    op.drop_table("certification_bodies")
    # Giá trị enum issuer_email / internal_consistency không gỡ được (PostgreSQL không hỗ trợ).
    # ### end Alembic commands ###
