"""identity checks blocklist

Revision ID: 0054
Revises: 0053
Create Date: 2026-09-30 10:57:32.511943
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0054"
down_revision: str | None = "0053"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocklist_identifiers",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "identifier_type",
            sa.Enum("tax_id", "domain", "phone", "file_sha256", name="blocklist_identifier_type"),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("added_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["added_by"], ["users.id"], name=op.f("fk_blocklist_identifiers_added_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocklist_identifiers")),
        sa.UniqueConstraint("identifier_type", "value", name="type_value"),
    )
    op.create_table(
        "evidence_checks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column(
            "subject",
            sa.Enum("legal_entity", "ownership", "evidence", name="evidence_check_subject"),
            nullable=False,
        ),
        sa.Column(
            "check_type",
            sa.Enum(
                "registry_lookup", "phone_callback", "email_domain", name="evidence_check_type"
            ),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.Enum("match", "mismatch", "not_found", "unchecked", name="evidence_check_result"),
            nullable=False,
        ),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("snapshot_key", sa.String(length=512), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("checked_by", sa.Uuid(), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checked_by"], ["users.id"], name=op.f("fk_evidence_checks_checked_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_evidence_checks_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidences.id"], name=op.f("fk_evidence_checks_evidence_id_evidences")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_checks")),
    )
    op.create_index(
        op.f("ix_evidence_checks_company_id"), "evidence_checks", ["company_id"], unique=False
    )
    # forbid_mutation() tạo ở migration 0002: kết quả kiểm chỉ ghi thêm (AGENTS.md §7).
    op.execute(
        "CREATE TRIGGER evidence_checks_append_only BEFORE UPDATE OR DELETE "
        "ON evidence_checks FOR EACH ROW EXECUTE FUNCTION forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER evidence_checks_no_truncate BEFORE TRUNCATE "
        "ON evidence_checks FOR EACH STATEMENT EXECUTE FUNCTION forbid_mutation()"
    )
    op.add_column("evidences", sa.Column("file_sha256", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_evidences_file_sha256"), "evidences", ["file_sha256"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidences_file_sha256"), table_name="evidences")
    op.drop_column("evidences", "file_sha256")
    op.drop_index(op.f("ix_evidence_checks_company_id"), table_name="evidence_checks")
    op.drop_table("evidence_checks")
    op.drop_table("blocklist_identifiers")
    for enum in (
        "evidence_check_subject",
        "evidence_check_type",
        "evidence_check_result",
        "blocklist_identifier_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum}")
    # ### end Alembic commands ###
