import { describe, expect, it } from 'vitest';
import { translateText } from '@/i18n/translate';

// Chuỗi mới thêm ở A1 phải có bản tiếng Anh trong catalog cũ (tr()), tới khi A3 chuyển sang next-intl.
const A1_STRINGS = [
  'Tài khoản tạm khóa 15 phút do đăng nhập sai nhiều lần.',
  'Mật khẩu cần ít nhất 10 ký tự.',
  'Vui lòng đồng ý Điều khoản sử dụng và Chính sách bảo mật.',
  'Không kết nối được máy chủ. Vui lòng thử lại.',
  'Thông tin chưa hợp lệ. Vui lòng kiểm tra lại.',
  'Ít nhất 10 ký tự',
  'Mật khẩu được mã hóa và phiên đăng nhập được bảo vệ phía máy chủ.',
  'Tôi đồng ý với Điều khoản sử dụng và Chính sách bảo mật của nền tảng.',
];

// Chuỗi mới ở B1 (form hồ sơ doanh nghiệp).
const B1_STRINGS = [
  'Ngôn ngữ nhân viên sử dụng',
  'Mô tả doanh nghiệp (tiếng Việt)',
  'Mô tả doanh nghiệp (tiếng Anh)',
  'Tiếng Việt',
  'Tiếng Anh',
  'Tiếng Trung',
  'Tiếng Nhật',
  'Tiếng Hàn',
  'Tiếng Pháp',
  'Tiếng Đức',
  'Thực phẩm & Đồ uống',
  'Dệt may',
  'Thủ công mỹ nghệ',
  'Thông tin doanh nghiệp chưa hợp lệ. Vui lòng kiểm tra lại.',
];

// Chuỗi mới ở B2 (form hồ sơ buyer).
const B2_STRINGS = [
  'Chọn quốc gia',
  'Mã số VAT',
  'Ví dụ: DE123456789',
  'Nhóm hàng cần tìm *',
  'Chọn một hoặc nhiều nhóm hàng bạn quan tâm.',
  'Ước lượng mua hàng mỗi năm',
  'Chọn mức ước lượng',
  'Dưới 100.000 EUR/năm',
  '100.000 – 500.000 EUR/năm',
  '500.000 – 2 triệu EUR/năm',
  '2 – 10 triệu EUR/năm',
  'Trên 10 triệu EUR/năm',
  'Vui lòng chọn ít nhất một nhóm hàng cần tìm.',
  'Vui lòng chọn quốc gia từ danh sách.',
  'Nhóm hàng',
  'Ước lượng mua hàng'
];

// Chuỗi mới ở B4 (ô chọn mã HS).
const B4_STRINGS = [
  'Gõ tên sản phẩm hoặc mã HS, ví dụ: gạo, rice, 1006',
  'Đã hỗ trợ máy tính',
  'Chưa hỗ trợ máy tính',
  'Không tìm thấy mã HS phù hợp',
  'Không tải được danh sách mã HS. Vui lòng thử lại.'
];

// Chuỗi mới ở B5 (sản phẩm, thị trường xuất khẩu). Mẫu có tên sản phẩm được thay bằng ví dụ cụ thể.
const B5_STRINGS = [
  'Chưa có sản phẩm. Hãy thêm ít nhất một sản phẩm kèm mã HS để buyer tìm thấy bạn.',
  'Sản phẩm',
  'Ví dụ: Gạo thơm Jasmine xuất khẩu',
  'Mã HS',
  'Giá thấp nhất',
  'Giá cao nhất',
  'Tiền tệ',
  'Đơn vị giá',
  'Chọn đơn vị',
  'MOQ (số lượng đặt tối thiểu)',
  'Đơn vị MOQ',
  'Mô tả (tiếng Việt)',
  'Mô tả (tiếng Anh)',
  'Ảnh sản phẩm',
  'Ảnh',
  'Xóa ảnh',
  'Đang tải…',
  'Thêm ảnh',
  'Đã đủ 10 ảnh',
  'Hiển thị công khai',
  'Cái',
  'Thùng',
  'Lít',
  'Ảnh phải là PNG, JPEG hoặc WebP.',
  'Ảnh tối đa 5MB.',
  'Không tải được ảnh lên. Bạn vẫn có thể lưu sản phẩm không có ảnh.',
  'Vui lòng thêm ít nhất một sản phẩm.',
  'Sản phẩm chưa hợp lệ. Vui lòng kiểm tra lại.',
  'Thị trường xuất khẩu đã phục vụ',
  'Mỗi sản phẩm cần có mã HS. Buyer tìm thấy bạn qua mã HS, giá và MOQ.',
  'Mỗi sản phẩm cần có tên.',
  'Giá thấp nhất không được lớn hơn giá cao nhất.',
  'Chưa có hồ sơ doanh nghiệp. Hãy lưu thông tin doanh nghiệp trước.',
  'Không tải được danh sách sản phẩm. Vui lòng thử lại.',
  'Chưa có sản phẩm. Thêm sản phẩm kèm mã HS để buyer tìm thấy bạn.',
  'Đang ẩn',
  'Giá:',
  'Từ',
  'Đến',
  'Sản phẩm "Gạo thơm" chưa chọn mã HS.',
  'Sản phẩm "Gạo thơm" chưa hợp lệ. Vui lòng kiểm tra mã HS, giá và ảnh.',
  'Không lưu được sản phẩm "Gạo thơm". Vui lòng thử lại.',
  'Giá thấp nhất không hợp lệ (số dương, dùng dấu chấm cho phần thập phân, tối đa 2 chữ số).'
];

// Chuỗi mới ở B3 (mô hình kinh doanh, EORI, thẻ hoàn thiện hồ sơ).
const B3_STRINGS = [
  'Mô hình kinh doanh *',
  'Mô hình kinh doanh',
  'Chọn mô hình',
  'Nhà sản xuất',
  'Công ty thương mại',
  'Vừa sản xuất vừa thương mại',
  'Mô hình:',
  'Mã EORI',
  'Ví dụ: DE123456789012345',
  'Mức độ hoàn thiện hồ sơ',
  'Đang tính điểm hoàn thiện…',
  'Không tải được điểm hoàn thiện hồ sơ.',
  'hoàn thiện',
  'Hồ sơ đã đầy đủ thông tin cần thiết.',
  'Việc cần bổ sung',
  'Điểm này chỉ đo mức đầy đủ của hồ sơ, không phải kết quả xác minh.',
  'Mã số thuế / ĐKKD',
  'Năm thành lập',
  'Địa chỉ',
  'Mô tả tiếng Anh (≥ 150 ký tự)',
  'Mô tả tiếng Việt (≥ 150 ký tự)',
  'Ngành hàng',
  'Thị trường xuất khẩu',
  'Ngoại ngữ nhân viên',
  'Sản phẩm kèm mã HS',
  'Ảnh sản phẩm',
  'Mô tả sản phẩm (≥ 30 ký tự)',
  'Giá sản phẩm',
  'Bằng chứng đã nộp',
  'Nhóm hàng quan tâm',
  'Mã VAT hoặc EORI',
  'Quy mô công ty',
  'Ước lượng mua hàng',
  'Loại hình doanh nghiệp'
];

const A2_STRINGS = [
  'Giấy phép và chứng nhận chưa được lưu lên hệ thống ở phiên bản này; phần tải lên thật sẽ được bổ sung sau. Bạn vẫn có thể hoàn tất hồ sơ với công ty và sản phẩm.',
  'Không thể lưu sản phẩm. Vui lòng thử lại.'
];

const C2_STRINGS = [
  'Kết quả',
  'Tiết kiệm mỗi lô',
  'Thuế MFN',
  'Thuế EVFTA',
  'Tiết kiệm mỗi năm',
  'Mã HS này chưa được hỗ trợ. Vui lòng liên hệ để được tư vấn.',
  'Trường hợp này cần kiểm tra thêm (ví dụ hạn ngạch hoặc thuế tuyệt đối), nên chúng tôi không đưa ra con số.',
  'Kết quả chỉ mang tính tham khảo, không thay thế tư vấn pháp lý hoặc xác nhận của cơ quan hải quan.',
  'Xem nhà cung cấp cho mã HS này',
  'Máy tính tiết kiệm thuế EVFTA',
  'Nhập mã HS, nước EU nhập khẩu và giá trị lô hàng để ước tính thuế nhập khẩu tiết kiệm được nhờ EVFTA.',
  'Sản phẩm (mã HS)',
  'Nước EU nhập khẩu',
  'Giá trị lô hàng (EUR)',
  'Số lô hàng mỗi năm (không bắt buộc)',
  'Tính tiết kiệm thuế',
  'Đang tính...',
  'Bạn đã tính quá nhiều lần. Vui lòng thử lại sau một phút.',
  'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại mã HS, nước nhập khẩu và giá trị lô hàng.',
  'Không kết nối được máy chủ. Vui lòng thử lại.',
  'Vui lòng chọn mã HS.',
  'Giá trị lô hàng phải là số dương, tối đa 2 chữ số thập phân (ví dụ 10000 hoặc 10000.50).',
  'Số lô hàng mỗi năm phải là số nguyên từ 1 đến 10000.'
];

const C4_STRINGS = [
  'Bạn đã kiểm tra quá nhiều lần. Vui lòng thử lại sau một phút.',
  'Dữ liệu chưa hợp lệ. Vui lòng kiểm tra lại mã HS, giá xuất xưởng và nguyên liệu.',
  'Trường hợp này cần chuyên gia đánh giá nên hệ thống không tự kết luận.',
  'Có nhiều hơn một quy tắc cho mã HS này nên cần chuyên gia đánh giá.',
  'Bạn chưa khai nguyên liệu nên chưa thể kết luận.',
  'Còn thiếu dữ liệu để kết luận (ví dụ giá xuất xưởng hoặc mã HS của nguyên liệu).',
  'Đạt',
  'Không đạt',
  'Chưa kết luận',
  'Chưa hỗ trợ',
  'Mã HS này nằm ngoài phạm vi dữ liệu của hệ thống. Điều đó không có nghĩa là hàng hóa không có quy tắc xuất xứ; vui lòng liên hệ để được tư vấn.',
  'Nguyên liệu không xuất xứ (NOM)',
  'Ngưỡng tối đa',
  'Kết quả chỉ mang tính tham khảo. Cơ quan cấp chứng nhận xuất xứ chính thức là Bộ Công Thương.',
  'Vui lòng chọn mã HS.',
  'Giá xuất xưởng phải là số dương, tối đa 2 chữ số thập phân (ví dụ 1000 hoặc 1000.50).',
  'Máy tính quy tắc xuất xứ EVFTA',
  'Kiểm tra hàng Việt Nam xuất sang EU có đạt quy tắc xuất xứ hay không. Mọi số tiền dùng cùng một đơn vị tiền tệ.',
  'Giá xuất xưởng (EXW)',
  'Nguyên liệu nhập khẩu',
  'Chưa khai nguyên liệu',
  'Không có nguyên liệu nhập khẩu',
  'Có nguyên liệu nhập khẩu (khai bên dưới)',
  'Nguyên liệu',
  'Nước xuất xứ (mã 2 chữ cái)',
  'Giá trị nguyên liệu',
  'Mã HS nguyên liệu (nếu có)',
  'Xóa nguyên liệu',
  'Thêm nguyên liệu',
  'Đang kiểm tra...',
  'Kiểm tra xuất xứ'
];

const C6_STRINGS = [
  'Chưa nộp',
  'Chờ duyệt',
  'Đã duyệt',
  'Hết hạn',
  'Bị từ chối',
  'Bằng chứng do quản trị viên xem xét và duyệt. Nộp đủ bằng chứng không phải kết quả xác minh doanh nghiệp.',
  'Danh sách kiểm theo nhóm hàng',
  'Thêm sản phẩm có mã HS để xem những bằng chứng cần nộp cho nhóm hàng của bạn.',
  'Bắt buộc',
  'Chỉ nhắc',
  'Bằng chứng đã nộp',
  'Chưa có bằng chứng nào. Chọn loại bằng chứng bên dưới và tải file lên.',
  'Số chứng chỉ',
  'Tổ chức cấp',
  'Ngày cấp',
  'Ngày hết hạn',
  'Lý do từ chối',
  'Xem file',
  'Xóa',
  'Nộp bằng chứng mới',
  'Loại bằng chứng',
  'Chọn loại',
  'Hạn dùng do hệ thống tự tính',
  'tháng kể từ ngày cấp.',
  'File bằng chứng',
  'PDF, PNG hoặc JPEG, tối đa 10MB.',
  'Nộp bằng chứng',
  'Vui lòng chọn loại bằng chứng.',
  'Vui lòng chọn file bằng chứng.',
  'Vui lòng nhập ngày cấp.',
  'Ngày cấp không được ở tương lai.',
  'Ngày hết hạn phải sau ngày cấp.',
  'File phải là PDF, PNG hoặc JPEG.',
  'File tối đa 10MB.',
  'Không tải được file lên. Vui lòng thử lại.',
  'Bằng chứng chưa hợp lệ. Vui lòng kiểm tra loại, ngày cấp, ngày hết hạn và file.',
  'Không nộp được bằng chứng. Vui lòng thử lại.',
  'Không xóa được bằng chứng. Vui lòng thử lại.',
  'Không kết nối được máy chủ. Vui lòng thử lại.'
];

const C7_STRINGS = [
  'Trạng thái xác minh do quản trị viên quyết định. Từ chối và yêu cầu bổ sung phải có lý do; doanh nghiệp sẽ thấy lý do này.',
  'Vui lòng nhập lý do.',
  'Không tải được hàng đợi. Vui lòng thử lại.',
  'Không có hồ sơ nào đang chờ duyệt.',
  'Gửi lúc',
  'MST',
  'Quốc gia',
  'Chưa nộp bằng chứng.',
  'Duyệt bằng chứng',
  'Từ chối bằng chứng',
  'Lý do từ chối bằng chứng',
  'Lý do quyết định (bắt buộc khi từ chối hoặc yêu cầu bổ sung)',
  'Duyệt xác minh',
  'Yêu cầu bổ sung',
  'Từ chối',
  'Yêu cầu này đã được xử lý hoặc công ty không còn ở trạng thái chờ duyệt.',
  'Cần nhập lý do khi từ chối hoặc yêu cầu bổ sung.',
  'Không tìm thấy yêu cầu.',
  'Cần nhập lý do khi từ chối bằng chứng.',
  'Không tìm thấy bằng chứng.',
  'Không tìm thấy dòng dữ liệu.',
  'Dòng đã duyệt không xóa được.',
  'Dữ liệu chưa duyệt không bao giờ hiện ra công khai và không được máy tính tuân thủ dùng. Sửa dữ liệu đã duyệt sẽ đưa nó về chưa duyệt.',
  'Dữ liệu tuân thủ',
  'Dòng thuế',
  'Quy tắc xuất xứ',
  'Loại bằng chứng',
  'Luật bằng chứng theo nhóm hàng',
  'Mã HS',
  'Nơi đến',
  'Loại thuế',
  'Hạn ngạch',
  'Hiệu lực',
  'Loại quy tắc',
  'Ngưỡng NOM',
  'Cần chuyên gia',
  'Mã',
  'Tên',
  'Nhóm',
  'Hạn (tháng)',
  'Đang bật',
  'Nhóm hàng',
  'Mức độ',
  'Ghi chú',
  'Có',
  'Không',
  'Bắt buộc',
  'Chỉ nhắc',
  'Trạng thái',
  'Chưa duyệt',
  'Duyệt',
  'dòng chưa duyệt',
  'Không tải được dữ liệu. Vui lòng thử lại.',
  'Chưa có dữ liệu. Nhập bằng script CSV rồi quay lại để duyệt.',
  'Quản trị',
  'Chờ duyệt'
];

const D2_STRINGS = [
  "Bạn đã hỏi quá nhiều lần. Vui lòng thử lại sau một phút.",
  "Câu hỏi chưa hợp lệ. Vui lòng nhập ít nhất 3 ký tự.",
  "Độ tin cậy cao",
  "Độ tin cậy trung bình",
  "Độ tin cậy thấp",
  "Ngoài phạm vi",
  "Câu trả lời",
  "Chúng tôi chưa đủ căn cứ trong tài liệu đã duyệt để trả lời câu hỏi này.",
  "Nguồn trích dẫn",
  "Trợ lý chỉ trả lời từ tài liệu đã được duyệt và không thay thế tư vấn pháp lý.",
  "Cảm ơn phản hồi của bạn.",
  "Câu trả lời có hữu ích không?",
  "Hữu ích",
  "Chưa hữu ích",
  "Không gửi được phản hồi. Vui lòng thử lại.",
  "Đã chuyển câu hỏi cho chuyên gia. Chúng tôi sẽ liên hệ qua email của bạn.",
  "Email nhận phản hồi từ chuyên gia",
  "Chuyển chuyên gia",
  "Vui lòng nhập email hợp lệ để chuyên gia liên hệ.",
  "Không gửi được yêu cầu. Vui lòng thử lại.",
  "Trợ lý tuân thủ EVFTA",
  "Hỏi về thuế, quy tắc xuất xứ và thủ tục EVFTA. Mọi câu trả lời đều có trích dẫn từ tài liệu đã được duyệt.",
  "Câu hỏi của bạn",
  "Vui lòng không nhập thông tin cá nhân vào câu hỏi.",
  "Mã HS liên quan (không bắt buộc)",
  "Đang trả lời...",
  "Hỏi trợ lý"
];

const D3_STRINGS = [
  "Đã chuyển chuyên gia",
  "Có lỗi",
  "Tài liệu của trợ lý",
  "Trợ lý chỉ dùng tài liệu đã duyệt. Nạp lại nội dung sẽ đưa tài liệu về trạng thái chưa duyệt.",
  "Chưa có tài liệu. Nạp corpus bằng lệnh ingest rồi quay lại để duyệt.",
  "đoạn",
  "Đã duyệt",
  "Mức tin cậy",
  "Câu hỏi gần đây",
  "Mẫu rà soát hằng tuần",
  "Chưa có câu hỏi nào ở mức tin cậy này.",
  "Tuần này chưa có câu hỏi nào để rà soát.",
  "Trợ lý AI",
  "Không tìm thấy tài liệu.",
  "Câu hỏi AI trong 7 ngày",
  "Chưa có câu hỏi nào gửi tới trợ lý AI trong 7 ngày qua.",
  "Độ tin cậy AI trung bình",
  "Thang 1 (thấp) đến 3 (cao). Chưa tính câu ngoài phạm vi."
];

const E2_STRINGS = [
  "Đã xác minh",
  "Sản phẩm",
  "Yêu cầu báo giá",
  "Xem hồ sơ",
  "Nhà cung cấp Việt Nam đã xác minh",
  "Chỉ những doanh nghiệp đã được xác minh mới xuất hiện trong danh bạ.",
  "Tìm theo tên công ty, sản phẩm, mã HS hoặc chứng nhận",
  "Mã HS",
  "Quốc gia",
  "Tất cả",
  "Nhóm hàng",
  "Chứng nhận",
  "Tìm kiếm",
  "Không tải được danh bạ. Vui lòng thử lại.",
  "Chưa có nhà cung cấp phù hợp. Hãy thử bỏ bớt bộ lọc hoặc đổi từ khóa.",
  "nhà cung cấp",
  "Phân trang",
  "Trang trước",
  "Trang sau",
  "Quay lại danh bạ",
  "Thành lập",
  "Doanh nghiệp chưa đăng sản phẩm nào.",
  "Nông sản",
  "Thủy sản",
  "Thực phẩm & Đồ uống",
  "Dệt may",
  "Thủ công mỹ nghệ",
  "Gia vị & Hương liệu"
];

const H1_STRINGS = [
  "Thông báo",
  "chưa đọc",
  "Đánh dấu tất cả đã đọc",
  "Không tải được thông báo. Vui lòng thử lại.",
  "Chưa có thông báo. Khi có yêu cầu báo giá, tin nhắn hoặc thay đổi xác minh, bạn sẽ thấy ở đây.",
  "Hồ sơ của bạn đã được xác minh.",
  "Yêu cầu xác minh của bạn bị từ chối.",
  "Quản trị viên cần bạn bổ sung thông tin để xác minh.",
  "Xác minh của bạn đã hết hạn.",
  "Trạng thái xác minh của bạn đã thay đổi.",
  "Xác minh của bạn sắp hết hạn.",
  "Bạn có yêu cầu báo giá mới.",
  "Bạn có tin nhắn mới.",
  "Có nhà cung cấp mới phù hợp với tìm kiếm của bạn."
];

const F1_STRINGS = [
  "Yêu cầu báo giá",
  "Bạn đã gửi quá nhiều yêu cầu báo giá hôm nay. Vui lòng thử lại vào ngày mai.",
  "Vui lòng hoàn thiện hồ sơ doanh nghiệp của bạn trước khi gửi yêu cầu báo giá.",
  "Sản phẩm này hiện không còn nhận yêu cầu báo giá.",
  "Thông tin chưa hợp lệ. Vui lòng kiểm tra lại số lượng, giá, ngày cần hàng và điểm đến.",
  "Chỉ tài khoản buyer đã đăng nhập mới gửi được yêu cầu báo giá.",
  "Đăng nhập bằng tài khoản buyer để gửi yêu cầu báo giá cho nhà cung cấp này.",
  "Đăng nhập",
  "Đăng ký buyer",
  "Chỉ tài khoản buyer mới gửi được yêu cầu báo giá.",
  "Đã gửi yêu cầu báo giá tới",
  "Xem các yêu cầu đã gửi",
  "Số lượng phải là số dương, tối đa 2 chữ số thập phân.",
  "Giá mục tiêu phải là số dương, tối đa 2 chữ số thập phân.",
  "Vui lòng nhập đơn vị tính.",
  "Vui lòng chọn ngày cần hàng.",
  "Sản phẩm",
  "Số lượng",
  "Đơn vị",
  "Giá mục tiêu (không bắt buộc)",
  "Tiền tệ",
  "Điều kiện giao hàng (Incoterms)",
  "Ngày cần hàng",
  "Quốc gia nhận hàng",
  "Cảng nhận hàng (không bắt buộc)",
  "Lời nhắn (không bắt buộc)",
  "Đang gửi...",
  "Gửi yêu cầu báo giá",
  "Mới",
  "Đã xem",
  "Đã báo giá",
  "Đóng",
  "Không đổi được trạng thái. Vui lòng thử lại.",
  "Không tải được danh sách yêu cầu báo giá. Vui lòng thử lại.",
  "Bạn chưa gửi yêu cầu báo giá nào. Tìm nhà cung cấp trong danh bạ và bấm \"Yêu cầu báo giá\".",
  "Chưa có yêu cầu báo giá nào. Hoàn thiện hồ sơ và xác minh doanh nghiệp để buyer tìm thấy bạn.",
  "Giá mục tiêu",
  "Điểm đến",
  "Đánh dấu",
  "Yêu cầu báo giá đã gửi",
  "Đăng nhập bằng tài khoản buyer để xem các yêu cầu báo giá."
];

const F2_STRINGS = [
  "Xem bản gốc",
  "Xem bản dịch",
  "Nội dung hội thoại",
  "Không tải được tin nhắn. Vui lòng thử lại.",
  "Chưa có tin nhắn. Hãy gửi lời chào đầu tiên; tin nhắn sẽ được dịch sang ngôn ngữ của người nhận.",
  "Không gửi được tin nhắn. Vui lòng thử lại.",
  "Tin nhắn",
  "Gửi",
  "Hội thoại",
  "Đăng nhập để xem hội thoại của bạn.",
  "Không tải được danh sách hội thoại. Vui lòng thử lại.",
  "Chưa có hội thoại nào. Hội thoại được mở tự động khi có yêu cầu báo giá.",
  "Danh sách hội thoại",
  "Mở hội thoại",
  "Bạn có tin nhắn mới."
];

const J2_STRINGS = [
  "Mật khẩu không đúng.",
  "Tài khoản quản trị không xóa được tại đây.",
  "Tài khoản của tôi",
  "Đăng nhập để quản lý tài khoản.",
  "Vui lòng nhập mật khẩu để xác nhận.",
  "Xóa tài khoản",
  "Email, số điện thoại và thông tin liên hệ của công ty sẽ bị xóa; công ty của bạn không còn xuất hiện trong danh bạ. Nhật ký thao tác được giữ lại để phục vụ kiểm toán nhưng không còn gắn với email của bạn. Việc này không thể hoàn tác.",
  "Xóa tài khoản của tôi",
  "Nhập mật khẩu để xác nhận",
  "Đang xóa...",
  "Xóa vĩnh viễn",
  "Hủy"
];

describe('catalog.json có bản tiếng Anh cho chuỗi A1, B1, B2, B3, B4, B5, A2, C2, C4, C6, C7, D2, D3, E2, H1, F1, F2, J2', () => {
  it.each([...A1_STRINGS, ...B1_STRINGS, ...B2_STRINGS, ...B3_STRINGS, ...B4_STRINGS, ...B5_STRINGS, ...A2_STRINGS, ...C2_STRINGS, ...C4_STRINGS, ...C6_STRINGS, ...C7_STRINGS, ...D2_STRINGS, ...D3_STRINGS, ...E2_STRINGS, ...H1_STRINGS, ...F1_STRINGS, ...F2_STRINGS, ...J2_STRINGS])('%s', (vi) => {
    const en = translateText(vi, 'en');
    expect(en).not.toBe(vi);
    expect(en.trim()).not.toBe('');
  });
});
